# Generated by Django 5.2 on 2026-08-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('STATUS_CHANGED', 'Status changed'), ('PRIORITY_CHANGED', 'Priority changed'), ('DELETED', 'Deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='new_value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='old_value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To do'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'complete')], default='TODO', max_length=20),
        ),
    ]
