# Generated by Django 5.2 on 2026-08-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_activitylog_action_alter_activitylog_new_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('TITLE_CHANGED', 'Title Changed'), ('DES_CHANGED', 'Description Changed'), ('STATUS_CHANGED', 'Status changed'), ('PRIORITY_CHANGED', 'Priority changed'), ('DUE_DATE_CHANGED', 'Due date changed'), ('DELETED', 'Deleted')], max_length=20),
        ),
    ]
