# Generated by Django 5.2 on 2026-08-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To do'), ('COMPLETED', 'complete')], default='TODO', max_length=20),
        ),
    ]
