# Generated by Django 5.2 on 2026-08-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_is_deleted_alter_activitylog_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='task_id',
            field=models.IntegerField(default=-1),
        ),
    ]
