# Generated by Django 5.2 on 2026-08-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='task_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
